---
env:
  global:
  - secure: |-
      dwzELGWFxyL4O2IutQ6oUciDk03QrhkoS8CP9CKgY4RkJJ/SWGEIT4CNaxRP
      aUCGYyB8g2y/qsX2AUY20s15288kEPSH3qRdNKnSjoo4xBtqMllgnMOUgB57
      ZC5GaYxrAlJ0gfAoftB0KfibmrK1GiYJFmYQfa08gi2Vg7LvJwo=
language: java
jdk:
- openjdk7
after_success:
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- echo "Host heroku.com" >> ~/.ssh/config
- echo "   StrictHostKeyChecking no" >> ~/.ssh/config
- echo "   CheckHostIP no" >> ~/.ssh/config
- echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
- heroku keys:clear
- yes | heroku keys:add
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then git remote add heroku git@heroku.com:centerdevice-roca.git;
  yes | git push heroku master;fi
